version: '3.7'
services:
  apiv4:
    build: .
    command: python -u app.py "mongo-db"
    ports:
      - 5000:5000
    volumes:
      - .:/todo 
    links:
      - db

  db:
    image: mongo:latest
    hostname: mongo-db
    ports:
      - 27017:27017
